name: Project 4A Animation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Surge
      run: npm install --global surge

    - name: Deploy to Surge
      run: surge ./build project-4a-by-gopal.surge.sh/ --token ${{ secrets.SURGE_TOKEN }}
